config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :auctions do
    resources :bids
    resources :publishings, only: :create
    resources :watches, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create] do
    resources :watches, only: [:index]
  end

  resources :sessions, only: [:new, :create] do
   delete :destroy, on: :collection
 end

 root 'welcome#index'
end

app/models/auction.rb
class Auction < ApplicationRecord
  belongs_to :user
  has_many :bids, dependent: :destroy

  has_many :watches, dependent: :destroy
  has_many :watchers, through: :watches, source: :user
  validates :title, presence: true
  validates :details, presence: true
  validates :end_date, presence: true
  validates :reserve_price, presence: true
  # validates :current_price, presence: true

  include AASM

  aasm whiny_transitions: false do
    state :draft, initial: true
    state :published
    state :reserve_met
    state :won
    state :cancelled
    state :reserve_not_met

    event :publish do
      transitions from: :draft, to: :published
    end

    event :meet do
      transitions from: [:published, :reserve_not_met], to: :reserve_met
    end

    event :unmeet do
      transitions from: [:published, :reserve_met], to: :reserve_not_met
    end

    event :win do
      transitions from: [:published, :reserve_met], to: :won
    end

    event :cancel do
      transitions from: [:published, :reserve_met, :reserve_not_met, :won], to: :cancelled
    end

    event :relaunch do
      transitions from: :cancelled, to: :draft
    end

  end

  def watched_by?(user)
    watches.exists?(user:user)
  end

  def watch_for(user)
    watches.find_by(user:user)
  end


end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
before_action :authenticate_user!
before_action :find_auction, only: [:show, :edit, :update, :destroy]

  def new
    @auction = Auction.new
  end

  def create

    @auction = Auction.new auction_params
  
    if @auction.current_price == nil
      @auction.current_price == 1
    else
      @auction.current_price
    end
      @auction.user = current_user


    if @auction.save
      redirect_to auctions_path, notice: 'New Auction Created!'
    else

      render :new, alert: @auction.errors.full_messages.join(', ')
    end
  end


  def show

    @bids = @auction.bids
    @newbid = @auction.bids.new


  end


  def index
    @auctions = Auction.all.order("created_at DESC")
  end

  def edit
    if can? :edit, @auction
    else

    redirect_to auction_path(@auction), alert: 'access denied'
    end
  end

  def update
    if !(can? :edit, @auction)
    redirect_to auction_path(@auction), alert: 'access denied'

  elsif @auction.update(auction_params)
    redirect_to auctions_path, notice: 'Auction updated!'
  else
    render :edit, alert: 'Something went wrong!'
  end

end

  def destroy
    if can? :destroy, @auction
    @auction.destroy
    redirect_to auctions_path, notice:
    'Auction delete'
  else
    redirect_to auction_path(@auction), alert: 'access denied'
  end
  end




private

def find_auction
  @auction = Auction.find params[:id]
end

def auction_params
  params.require(:auction).permit([:title,:details, :end_date, :reserve_price, :current_price])
end

end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_form.html.erb
<%= simple_form_for @auction do |f| %>
<%= f.input :title %>
<%= f.input :details %>
<%= f.input :end_date, as: :date, html5: true %>
<%= f.input :reserve_price %>
<%= f.input :current_price %>
<%= f.submit class: 'btn btn-primary'%>

<% end %>

app/views/auctions/edit.html.erb
<h1>Edit Auction</h1>
<%= simple_form_for @auction do |f| %>
<%= f.input :title %>
<%= f.input :details %>
<%= f.input :end_date, as: :date, html5: true %>
<%= f.input :reserve_price %>
<%= f.input :current_price %>
<%= f.submit class: 'btn btn-primary'%>

<% end %>

app/views/auctions/index.html.erb
<h2>Current Auctions</h2>
<ul>
<% @auctions.each do |a| %>
<li><%= link_to a.title, auction_path(a) %><br>
Reserve Price: $ <%= a.reserve_price %></li>
<strong>Current Price: $ <%= a.current_price %></strong>
<p>Current State: <%= a.aasm_state %></p>
<% end %>
</ul>

app/views/auctions/new.html.erb
<h1>New Auction</h1>
<%= render 'form' %>

app/views/auctions/show.html.erb
<%= @auction.title %>
<%= @auction.details %>
<p>Created On: <%= @auction.created_at %></p>
<p>Owner: <%= @auction.user.first_name %></p>
<p>Reserve Price: $ <%= @auction.reserve_price %></li></p>
<strong><p> Current Price: $ <%= @auction.current_price %></strong></p>
<p>Current State: <%= @auction.aasm_state %></p>
<% if @auction.user == current_user %>
<p><%= link_to 'Edit', edit_auction_path(@auction) %>
<%= link_to 'Delete', auction_path(@auction), method: :delete, data: { confirm: "Are you sure?" }  %>
<% end %></p>


<% if @auction.user == current_user%>
<p>Auction Curret State: <%= @auction.aasm_state %>
<br>
<% if @auction.may_publish? %>
<%= link_to 'Publish', auction_publishings_path(@auction), method: :post %>
<% end %>
<% end %></p>





<% if user_signed_in? %>
<% if @auction.watched_by?(current_user) %>
<%= link_to fa_icon("heart"), auction_watch_path(@auction, @auction.watch_for(current_user)), method: :delete %>
<% else %>
<%= link_to fa_icon("heart-o"), auction_watches_path(@auction), method: :post%>
<% end %>
<% end %>

<hr>

<%= render 'bids/form' %>
<br>
<% @bids.each do |b| %>
<% if b.user_id %>
<strong>$ <%= b.price  %></strong>
<br>
Bid Sumitted by <%= b.user.first_name  %> <%= b.user.last_name  %>
On <%= b.created_at %>
<br><br>
<% if b.user == current_user %>
<%= link_to 'Edit', edit_auction_bid_path(b.auction, b) %>
<%= link_to 'Delete', auction_bid_path(b.auction, b), method: :delete, data: { confirm: "Are you sure?" }   %>
<% end %>
<hr>
<% end %>
<% end %>